# Generated by Django 4.2.7 on 2023-11-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0003_user_artist_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.DeleteModel(
            name='album',
        ),
        migrations.DeleteModel(
            name='artist',
        ),
    ]
